import { NextPage } from "next";
import Head from "next/head";
import { motion, useScroll } from "framer-motion";
import { useEffect, useState } from "react";

import HomeSection from "./Home/Home.Section";
import AboutSection from "./Home/About.Section";
import AgentSection from "./Home/Agent.Section";
import Layout from "@/templates/LandingPage/Layout";
import MapSection from "./Home/Map.Section";

const Index: NextPage = () => {
  const {scrollYProgress: Complete} = useScroll()

  return (
    <>
      <Head>
        <title>next-rhino-valorant</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="h-100vh overflow-y-hidden bg-white">
        {/* <motion.div
          className="fixed bg-red top-0 left-0 right-0 h-[15px]"
          style={{ scaleX: Complete }}
        /> */}
        <HomeSection />
        <AboutSection />
        <AgentSection />
        <MapSection />
        {/* <Layout /> */}
      </div>
    </>
  );
};

export default Index;
