import { NextPage } from "next";
import Head from "next/head";

const TestPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>next-rhino-valorant</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <TestPage />
    </>
  );
};

export default TestPage;
